#!/usr/local/bin/bash

while [[ $# -gt 0 ]]; do
 case "$1" in
  -o) MOCKS_CURL_OUTPUT_PATH="$2"; shift 2;;
  -w) MOCKS_CURL_OUTPUT_FORMAT="$2"; shift 2;;
  --data) MOCKS_CURL_DATA="$2"; shift 2;;
  *) shift;;
 esac
done

if [[ -n "${MOCKS_CURL_DATA}" && -n "${MOCKS_CURL_DATA_PATH}" ]]; then
 printf '%s' "${MOCKS_CURL_DATA}" > "${MOCKS_CURL_DATA_PATH}" || exit 1; fi

if [[ -n "${MOCKS_CURL_OUTPUT}" && -n "${MOCKS_CURL_OUTPUT_PATH}" ]]; then
 printf '%s' "${MOCKS_CURL_OUTPUT}" > "${MOCKS_CURL_OUTPUT_PATH}" || exit 1; fi

if [[ "${MOCKS_CURL_OUTPUT_FORMAT}" == '%{http_code}' ]]; then
 printf '%s' "${MOCKS_CURL_CODE}"; fi

if [[ "${MOCKS_CURL_EXIT_CODE}" =~ ^[1-9][0-9]*$ ]]; then
 exit ${MOCKS_CURL_EXIT_CODE}; fi
