#!/usr/local/bin/bash

if [[ $# -ne 3 ]]; then
 echo 'Wrong arguments!' >&2; exit 1; fi

MOCKS_STAT_F0="$1"
MOCKS_STAT_F1="$2"
MOCKS_STAT_PATH="$3"

if [[ "${MOCKS_STAT_EXIT_CODE}" =~ ^[1-9][0-9]*$ ]]; then
 exit ${MOCKS_STAT_EXIT_CODE}
elif [[ -n "${MOCKS_STAT_EXIT_CODE}" ]]; then
 echo 'Wrong exit code!' >&2; exit 1
elif [[ "${MOCKS_STAT_SIZE}" =~ ^(0|[1-9][0-9]*)$ ]]; then
 prinf '%s' ${MOCKS_STAT_SIZE}
elif [[ -n "${MOCKS_STAT_SIZE}" ]]; then
 echo 'Wrong size!' >&2; exit 1
else
 /usr/local/bin/stat "${MOCKS_STAT_F0}" "${MOCKS_STAT_F1}" "${MOCKS_STAT_PATH}"
fi
